body_balance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('shop_bag/', include('shop_bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('nutrition/', include('nutrition.urls')),
    path('subscriptions/', include('subscriptions.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'body_balance.views.handler404'
handler500 = 'body_balance.views.handler500'

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shop_all_products, name='shop_products'),
    path('<int:product_id>/', views.get_product_detail,
         name='get_product_detail'),
    path('add_product/', views.add_product_admin, name='add_product_admin'),
    path('edit_product/<int:product_id>/', views.edit_product_admin,
         name='edit_product_admin'),
    path('delete_product/<int:product_id>/', views.delete_product_admin,
         name='delete_product_admin'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from user_profile.models import UserProfile


class ProductOrder(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    shop_total = models.DecimalField(max_digits=10, decimal_places=2,
                                     null=False, default=0)
    original_shop_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False,
                                  default='')

    def get_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update shopping bag total each time an order is added to the queue,
        accounting for delivery costs.
        """

        self.order_total = self.lineorders.\
            aggregate(Sum('lineorder_total'))['lineorder_total__sum'] or 0

        if self.order_total < settings.FREE_DELIVERY:
            self.delivery_cost = self.order_total * settings.\
                DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.shop_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self.get_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class ProductLineOrder(models.Model):
    order = models.ForeignKey(ProductOrder, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineorders')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    # XS, S, M, L, XL
    product_size = models.CharField(max_length=2, null=True, blank=True)
    product_quantity = models.IntegerField(null=False, blank=False, default=0)
    lineorder_total = models.DecimalField(max_digits=6, decimal_places=2,
                                          null=False, blank=False,
                                          editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the product line order total
        and update the order total.
        """
        self.lineorder_total = self.product.price * self.product_quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    category_friendly_name = models.CharField(max_length=100)
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name

    def get_category_friendly_name(self):
        return self.category_friendly_name


class Product(models.Model):
    product_name = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=100, null=True, blank=True)
    product_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=3, decimal_places=1, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image_file = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.product_name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class AddProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image_file = forms.ImageField(label='Image File', required=False,
                                  widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        product_friendly_names = [(cat.id, cat.get_category_friendly_name())
                                  for cat in categories]

        self.fields['category'].choices = product_friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from user_profile.models import UserProfile
from shop_bag.contexts import bag_products
from .models import Product, Category
from .forms import AddProductForm


def check_user(request):
    """ check if user has nutrition plan """

    if request.user.is_authenticated:
        profile = get_object_or_404(UserProfile, user=request.user)
        has_plan = profile.has_plan
        return has_plan
    else:
        return 'AnonymousUser'


def shop_all_products(request):
    """ A view to show all products, including sorting and search queries """

    shop_products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None
    anon_message = 'Register to Buy Nutrition Plan'

    if request.GET:
        if 'sort' in request.GET:
            sort_key = request.GET['sort']
            sort = sort_key
            if sort_key == 'name':
                sort_key = 'lower_name'
                shop_products = shop_products.\
                    annotate(lower_name=Lower('product_name'))
            if sort_key == 'category':
                sort_key = 'category__category_name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sort_key = f'-{sort_key}'
            shop_products = shop_products.order_by(sort_key)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            shop_products = shop_products.\
                filter(category__category_name__in=categories)
            categories = Category.objects.filter(category_name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               "You didn't enter any search criteria!")
                return redirect(reverse('shop_products'))

            queries = Q(product_name__icontains=query) |\
                Q(description__icontains=query)
            shop_products = shop_products.filter(queries)

    #  check if user has nutrition plan
    has_plan = check_user(request)
    selected_sorting = f'{sort}_{direction}'

    context = {
        'products': shop_products,
        'search_term': query,
        'selected_categories': categories,
        'selected_sorting': selected_sorting,
        'has_plan': has_plan,
        'anon_message': anon_message,
    }

    return render(request, 'products/products.html', context)


def get_product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)

    current_bag = bag_products(request)
    bag_items = current_bag['bag_items']
    nutrition_in_bag = False

    for item in bag_items:
        if item["product_id"] == str(product_id):
            nutrition_in_bag = True

    context = {
        'product': product,
        'nutrition_in_bag': nutrition_in_bag,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product_admin(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners have the permission\
            to add products.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Product added successfully!')
            return redirect(reverse('get_product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed! Please ensure you added the\
                products correctly!')
    else:
        form = AddProductForm()

    template = 'products/add_product_admin.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product_admin(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners have the permission\
            to edit products.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('get_product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure\
                the form is valid.')
    else:
        form = AddProductForm(instance=product)
        messages.info(request, f'You are editing {product.product_name}')

    template = 'products/edit_product_admin.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product_admin(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners have the permission\
            to delete products.')
        return redirect(reverse('home'))
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product is deleted!')
    return redirect(reverse('shop_products'))

products/templates/products/add_product_admin.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container mob-margin mb-5">
        <div class="row">
            <div class="col-12 col-md-12">
                <h2 class="mb-4 text-center">Product Management</h2>
                <hr>
                <h5 class="text-muted text-uppercase mb-5">Add a Product</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-12">
                <form method="POST" action="{% url 'add_product_admin' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image_file' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-small" href="{% url 'shop_products' %}">Cancel</a>
                        <button class="btn btn-secondary btn-sm" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
        <a class="btn mt-3" href="#" onclick="window.history.back();"><span class="icon">
            <i class="fas fa-arrow-left"></i>
        </span> Back</a>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image-input').change(function() {
            var img_file = $('#new-image-input')[0].files[0];
            $('#filename').text(`Image will be set to: ${img_file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product_admin.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container mb-5 mob-margin">
        <div class="row">
            <div class="col-12 col-md-12">
                <h2 class="mb-4 text-center">Product Management</h2>
                <hr>
                <h5 class="text-muted text-uppercase mb-5">Edit a Product</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-12">
                <form method="POST" action="{% url 'edit_product_admin' product.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image_file' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-small" href="{% url 'shop_products' %}">Cancel</a>
                        <button class="btn btn-secondary btn-sm" type="submit">Update Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image-input').change(function() {
            var img_file = $('#new-image-input')[0].files[0];
            $('#filename').text(`Image will be set to: ${img_file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay-color"></div>
    <section class="container">
        <div class="row">
            <div class="col-12 mb-3 mt-5">
                <a href="{% url 'shop_products' %}" class="btn mt-5">
                    <span class="icon">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text-uppercase">Back to Shopping</span>
                </a>
            </div>
        </div>
        <div class="product-container product-detail-section mt-0 mb-5">
            <div class="row">
                <div class="col-12 col-md-8">
                    <div class="img-container">
                        {% if product.image_file %}
                            <a href="{{ product.image_file.url }}" target="_blank">
                                <img class="card-img-top img-fluid" src="{{ product.image_file.url }}" alt="{{ product.product_name }}">
                            </a>
                        {% else %}
                            <a href="">
                                <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.product_name }}">
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="product-detail-container mb-5">
                        {% if product.category %}
                            <p class="small mt-0 mb-1">
                                <a class="text-muted small" href="{% url 'shop_products' %}?category={{ product.category.category_name }}">
                                    <em>{{ product.category.category_friendly_name }}</em>
                                </a>
                            </p>
                        {% endif %}
                        <h3>{{ product.product_name }}</h3>
                        <div class="row">
                            <div class="col">
                                {% if product.rating %}
                                    <small class="my-rating" data-rating="{{ product.rating }}"></small>
                                {% else %}
                                    <small class="text-muted">No Rating</small>
                                {% endif %}
                            </div>
                        </div>
                        <p class="mt-3">{{ product.description }}</p>
                        <p class="price text-left">‎<small>€</small>{{ product.price }} <span class="{% if product.category.category_name == 'nutrition_plan' %} d-none {% endif %}"><small> + shipping </small></span></p>
                        <form class="form" action="{% url 'add_products_to_bag' product.id %}" method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                {% with product.product_sizes as size %}
                                    {% if size %}
                                        <div class="col-12">
                                            <p class="mt-3 mb-0">Select size</p>
                                            <div class="btn-group btn-group-toggle w-100" data-toggle="buttons" id='id_product_size'>
                                                <label class="btn btn-green active">
                                                    <input type="radio" value="xs"  name="product_size" id="xs"> XS
                                                </label>
                                                <label class="btn btn-green">
                                                    <input type="radio" value="s"  name="product_size" id="s" > S
                                                </label>
                                                <label class="btn btn-green">
                                                    <input type="radio"  value="m" name="product_size" id="m" checked> M
                                                </label>
                                                <label class="btn btn-green">
                                                    <input type="radio" value="l"  name="product_size" id="l" > L
                                                </label>
                                                <label class="btn btn-green">
                                                    <input type="radio"  value="xl" name="product_size" id="xl" > XL
                                                </label>
                                            </div>
                                        
                                        </div>
                                    {% endif %}
                                    <input class="form-control qty_input" type="hidden"
                                    name="quantity" value="1" min="1" max="1"
                                    data-item_id="{{ product.id }}"
                                    id="id_qty_{{ product.id }}">    
                                        <div class="container mt-5">
                                                
                                            {% if product.category.category_name == "nutrition_plan" %}
                                                {% if nutrition_in_bag %}
                                                    <div> <p>Item already in bag</p></div>
                                                    
                                                {% else %}
                                                <button type="submit" class="btn text-center add-to-cart w-100">
                                                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" > <path fill-rule="evenodd" clip-rule="evenodd" d="M5 4H19C19.5523 4 20 4.44771 20 5V19C20 19.5523 19.5523 20 19 20H5C4.44772 20 4 19.5523 4 19V5C4 4.44772 4.44771 4 5 4ZM2 5C2 3.34315 3.34315 2 5 2H19C20.6569 2 22 3.34315 22 5V19C22 20.6569 20.6569 22 19 22H5C3.34315 22 2 20.6569 2 19V5ZM12 12C9.23858 12 7 9.31371 7 6H9C9 8.56606 10.6691 10 12 10C13.3309 10 15 8.56606 15 6H17C17 9.31371 14.7614 12 12 12Z" fill="currentColor" /> </svg>
                                                    ADD TO BAG
                                                </button>
                                                {% endif %}
                                            {% else %}
                                                <button type="submit" class="btn text-center add-to-cart w-100">
                                                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" > <path fill-rule="evenodd" clip-rule="evenodd" d="M5 4H19C19.5523 4 20 4.44771 20 5V19C20 19.5523 19.5523 20 19 20H5C4.44772 20 4 19.5523 4 19V5C4 4.44772 4.44771 4 5 4ZM2 5C2 3.34315 3.34315 2 5 2H19C20.6569 2 22 3.34315 22 5V19C22 20.6569 20.6569 22 19 22H5C3.34315 22 2 20.6569 2 19V5ZM12 12C9.23858 12 7 9.31371 7 6H9C9 8.56606 10.6691 10 12 10C13.3309 10 15 8.56606 15 6H17C17 9.31371 14.7614 12 12 12Z" fill="currentColor" /> </svg>
                                                    ADD TO BAG
                                                </button>
                                            {% endif %}
                                                
                                            {% if request.user.is_superuser %}
                                                <div class="mt-5 ml-3 bg-light mx-auto d-block py-4 px-4">
                                                    
                                                    <a class="mt-1 text-danger small" href="{% url 'delete_product_admin' product.id %}">Delete</a>

                                                    <a class="btn btn-sm btn-secondary float-right " href="{% url 'edit_product_admin' product.id %}">Edit</a> 
                                                </div>
                                            {% endif %} 
                                            
                                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                        </div>
                                {% endwith %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/product_quantity_script.html' %}
<script src="{% static 'products/js/jquery.star-rating-svg.js' %}"></script>
<script>
    $(".my-rating").starRating({
        totalStars: 5,
        useGradient: false,
        readOnly: true,
        strokeColor: '#894A00',
        strokeWidth: 10,
        starSize: 25
    });
</script>
{% endblock %}